-- CAST to INT64
SELECT CAST(price AS INT64) FROM products

-- CAST to STRING
SELECT CAST(id AS STRING) FROM users

-- CAST to FLOAT64
SELECT CAST('123.45' AS FLOAT64) AS price

-- SAFE_CAST (returns NULL on error)
SELECT SAFE_CAST(value AS INT64) FROM data

-- CAST to TIMESTAMP
SELECT CAST('2024-01-01 12:00:00' AS TIMESTAMP) AS created_at
